### ISSUE TITLE
Revisit prerequisites

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#136] opened 2020-11-23 17:32 UTC
We say that, before following this lesson, learners should be able to:

-create a repository/project on GitHub and/or GitLab.
-clone a local copy of a project with Git, add and commit modified files, and push/pull changes between local and remote repositories.
-execute commands in the shell

However, we are not using git from shell in this lesson. I know we planned to add an episode on local build - if we are not doing this them we need to revisit preraquisites.

**Comment by tobyhodges** [comment] 2020-11-23 17:55
Closing this as a duplicate of #108

**Closed as completed by tobyhodges** 2020-11-23 17:55 UTC
